### ISSUE TITLE
Catch up 07-04

### ISSUE THREAD

**Issue by sheltonsuen** [thoughtworks-js-community-chengdu/js-catch-up#5]

**Comment by sheltonsuen** [comment]
Catch up前：
- 定会议室，发会议邀请
- 统计catch up人数，订饭
- 确定分享话题和分享人
- 确定zoom连接

Catch up中：
- 主持会议，
- 记录会议记录
- 拍照
- 收集反馈
- 确定下一次会议的owner

Catch up后
- 发出会议总结
- 记录下花费

其他需要知道的信息：
google driver:
https://drive.google.com/drive/u/1/folders/1EvaeJ2bj0pCnKLJQ1xgnDpVzSq1UJ8yd?ogsrc=32

**Comment by sheltonsuen** [comment]
@dcZhangTW 下一次的catch up 现在有自愿者么？

**Comment by dcZhangTW** [comment]
assign 给珂珂了
